# Generated by Django 3.1.7 on 2021-03-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(max_length=64)),
                ('task_type', models.IntegerField(choices=[(1, 'Tts'), (2, 'Voice')])),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
